# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mnoXJSazBt0nf6jQQXgPHI7s7dNvkkqi
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

st.title("📊 Generador de gráficos")

# 1. Elegir variables
x_label = st.text_input("Nombre del eje X", "X")
y_label = st.text_input("Nombre del eje Y", "Y")

# 2. Tipo de gráfico
tipo = st.selectbox("Tipo de gráfico", ["Y vs X", "X vs Y"])

# 3. Ingreso de datos
st.subheader("📥 Ingresar datos")

data = st.data_editor(
    pd.DataFrame({
        x_label: [],
        y_label: []
    }),
    num_rows="dynamic"
)

# 4. Botón para graficar
if st.button("📈 Generar gráfico"):

    if len(data) == 0:
        st.warning("Ingresá al menos un dato")
    else:
        x = data[x_label]
        y = data[y_label]

        # Invertir si el usuario quiere X vs Y
        if tipo == "X vs Y":
            x, y = y, x

        fig, ax = plt.subplots()

        ax.plot(x, y, marker='o')

        ax.set_xlabel(x_label)
        ax.set_ylabel(y_label)

        # Escala de 0.1
        ax.set_xticks(np.arange(min(x), max(x)+0.1, 0.1))
        ax.set_yticks(np.arange(min(y), max(y)+0.1, 0.1))

        ax.grid(True)

        st.pyplot(fig)